@echo off
REM clean.bat - Remove all auxiliary and temporary files generated by LaTeX compilation.

echo Cleaning auxiliary files...
del /Q *.aux
del /Q *.bbl
del /Q *.blg
del /Q *.glg
del /Q *.glo
del /Q *.gls
del /Q *.ist
del /Q *.loa
del /Q *.lof
del /Q *.lol
del /Q *.lot
del /Q *.toc
del /Q *.acn
del /Q *.acr
del /Q *.alg
del /Q *.out
del /Q *.log
del /Q *.fdb_latexmk
del /Q *.synctex.gz
del /Q *.fls
del /Q *.synctex(busy)
del /Q *.synctex.gz(busy)
del /Q *.bcf
del /Q *.run.xml

echo Cleaning .eps and .svg image folders...
rmdir /S /Q figures-converted 2>nul

echo Clean complete.
